Lesson1
Runidan/JavaScript pull request #1
Opened 2022-06-24 10:52 UTC by Runidan

2022-06-24 13:36 UTC, PonomareVlad approved these changes
Все задачи в этом Pull Request'е выполнены правильно ! 🙂

2022-06-24 13:36 UTC, PonomareVlad commented on revers.js
> +}
Отличное решение, вы первый, кто смог корректно преобразовать строку, содержащую Emoji 🎉

2022-06-24 15:01 UTC, PonomareVlad requested changes
Ошибка в решении первого задания

2022-06-24 15:01 UTC, PonomareVlad commented on first_task.txt
> +Порядок действий: *  +   =  x++
Уточните, правильно понимаю, что оператор присвоения (`=`) у вас идет после сложения (`+`) и перед инкрементом (`++`) ?

2022-06-24 15:11 UTC, Runidan commented on first_task.txt
> +Порядок действий: *  +   =  x++
Да. Я посчитал в ручную, а потом ввёл в командную строку и мой ответ не сошёлся. Я сделал вывод, что x++ отдаёт прежнее значение и когда происходит присвоение, увеличивается на единицу.

2022-06-24 15:19 UTC, PonomareVlad commented on first_task.txt
> +Порядок действий: *  +   =  x++
Давайте сопоставим это с таблицей https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Operators/Operator_Precedence#table

2022-06-24 15:37 UTC, Runidan commented on first_task.txt
> +Порядок действий: *  +   =  x++
В таблице инкремент выше сложения и тем более присвоения. Не понимаю, как тогда это соотнести с результатом? Увеличив x до семи z должно быть 82, а получается 81.

2022-06-24 20:43 UTC, PonomareVlad commented on first_task.txt
> +Порядок действий: *  +   =  x++
Похоже, вы упустили детали реализации инкрементов, попробуйте ознакомится с ними в [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Increment)

2022-06-25 11:09 UTC, Runidan commented on first_task.txt
> +Порядок действий: *  +   =  x++
Отредактировал

2022-06-25 11:10 UTC, PonomareVlad approved these changes
Все корректно ! 🙂

2022-06-27 08:34 UTC, merged