Lesson2
Runidan/JavaScript pull request #2
Opened 2022-06-28 12:42 UTC by Runidan

2022-06-30 00:17 UTC, PonomareVlad requested changes
Нужно исправить решения задач

2022-06-30 00:17 UTC, PonomareVlad commented on 1_words_to_array.js
> +      isCapitalized: word == word.toUpperCase(),
Похоже, имелась в виду [только первая буква](https://en.wikipedia.org/wiki/Capitalization) слова

2022-06-30 00:17 UTC, PonomareVlad commented on 2_comparison_arrays.js
> +}
Как можно учесть такой случай ?

```js
const a = [21, 34, -6, 10, -56];
const b = [100];
console.log(array_comparison(a, b));
console.log(array_comparison(b, a));
```

2022-06-30 00:17 UTC, PonomareVlad commented on 5_workers.js
> +  return (acc + item.salary) / 2;
Лучше использовать [Среднее арифметическое](https://ru.wikipedia.org/wiki/Среднее_арифметическое), т.к. при расчете в обратную сторону (с конца массива) результат будет отличатся:

```js
console.log(employees.reduce(reduceCallBack, employees[0].salary))
console.log(employees.reverse().reduce(reduceCallBack, employees[0].salary))
```

2022-06-30 00:17 UTC, PonomareVlad commented on 8.js
> +    return this.birthday.toLocaleDateString();
Проверьте формат, в котором вы сохраняете и выводите дату:

```js
human.dateOfBirth = '1980-05-06';
console.log(human.dateOfBirth); // TypeError
```

2022-06-30 07:27 UTC, Runidan commented on 1_words_to_array.js
> +      isCapitalized: word == word.toUpperCase(),
Исправил

2022-06-30 07:29 UTC, Runidan commented on 2_comparison_arrays.js
> +}
Добавил метод, который вместо undefined выдает -infinity. И итоговой массив равен по длине самому длинному из входящих

2022-06-30 07:29 UTC, Runidan commented on 5_workers.js
> +  return (acc + item.salary) / 2;
Исправил

2022-06-30 07:30 UTC, Runidan commented on 8.js
> +    return this.birthday.toLocaleDateString();
Исправил

2022-07-01 09:59 UTC, PonomareVlad approved these changes
Критических багов больше нет, все супер ! 🔥

2022-07-01 09:59 UTC, PonomareVlad commented on 1_words_to_array.js
> +      isCapitalized: word == word.toUpperCase(),
Задание выполнено корректно, опционально можете протестировать вашу функцию на [поддержку пунктуации](https://thinknetica.ponomarevlad.ru/2/1.html?url=https%3A%2F%2Fraw.githubusercontent.com%2FRunidan%2FJavaScript%2FLesson2%2F1_words_to_array.js&func=words_to_array#punctuation) и [разрыва строк](https://thinknetica.ponomarevlad.ru/2/1.html?url=https%3A%2F%2Fraw.githubusercontent.com%2FRunidan%2FJavaScript%2FLesson2%2F1_words_to_array.js&func=words_to_array#linebreak)

2022-07-01 09:59 UTC, PonomareVlad commented on 8.js
> +    return this.birthday.toLocaleDateString();
Отлично, также не забывайте что могут быть случаи, если пользователь [укажет только имя без фамилии](https://thinknetica.ponomarevlad.ru/2/8.html?url=https%3A%2F%2Fraw.githubusercontent.com%2FRunidan%2FJavaScript%2FLesson2%2F8.js#name) или если он использует [российский формат дат](https://thinknetica.ponomarevlad.ru/2/8.html?url=https%3A%2F%2Fraw.githubusercontent.com%2FRunidan%2FJavaScript%2FLesson2%2F8.js#date-ru)

2022-07-11 11:44 UTC, merged