Lesson4
Runidan/JavaScript pull request #5
Opened 2022-07-13 10:12 UTC by Runidan

2022-07-13 11:28 UTC, PonomareVlad requested changes
Нужно доработать решение **2-й** задачи

2022-07-13 11:28 UTC, PonomareVlad commented on Lesson4/1.js
> +Array.prototype.shuffle = function(){return this.sort(function() { return Math.random() - Math.random(); })};
Можно немного упростить вычисления и предотвратить перемешивание исходного массива:
```suggestion
Array.prototype.shuffle = function(){return [...this].sort(() => Math.random() - 0.5)};
```

```js
const array = [1, 2, 3];

console.debug(array.shuffle()); // [2, 1, 3]

console.debug(array); // [1, 2, 3]
```

2022-07-13 11:28 UTC, PonomareVlad commented on Lesson4/2.js
> +}
```js
new Rectangle(2, 2).getArea(); // 4

new Square(2).getArea(); // TypeError: new Square(2).getArea is not a function.
```

2022-07-13 11:28 UTC, PonomareVlad commented on Lesson4/3.js
> +Object.setPrototypeOf(former_employee, current_employee);
В текущей реализации, можно уволить (и не только) бывшего сотрудника:
```js
former_employee.retire // function () {}
```

2022-07-13 13:12 UTC, Runidan commented on Lesson4/2.js
> +}
Да, протайп не прописал. Добавил.

2022-07-13 20:25 UTC, PonomareVlad approved these changes
Решения для первого задания приняты 🎉

2022-07-13 20:31 UTC, PonomareVlad requested changes
Нужно доработать решение **второго** задания

2022-07-13 20:31 UTC, PonomareVlad commented on Lesson4/task2.js
> +}
Нет отдельных конструкторов для каждого типа верфи:

> **_Верфи_** и корабли должны создаваться с помощью **_функций-конструкторов_**.

2022-07-13 20:31 UTC, PonomareVlad commented on Lesson4/task2.js
> +  }
Дополнительную проверку на тип нового корабля можно исключить, т.к. конструктор каждой верфи уже связан только с соответствующим типом кораблей

2022-07-15 11:48 UTC, PonomareVlad commented
Отлично, а теперь т.к. это задание находится в части курса под названием **Прототипы** а не **Объекты и массивы** — предлагаю изменить способ проверки типа корабля: вместо указания свойства `type`, использовать проверку прототипа корабля 🙂

2022-07-16 18:39 UTC, PonomareVlad requested changes
Почти идеально 🎉

Осталось только немного сократить дублирующийся код

[Пример](https://github.com/PonomareVlad/Thinknetica/blob/main/4/2.mjs)

2022-07-18 16:41 UTC, PonomareVlad approved these changes
Безупречно 🙂

2022-07-19 08:05 UTC, merged