Lesson8
Runidan/JavaScript pull request #9
Opened 2022-08-14 14:42 UTC by Runidan

2022-08-16 08:48 UTC, PonomareVlad requested changes
> Можно создать уже выполненный промис с помощью CustomPromise.resolve/reject

Как можно проверить эту функциональность ?

2022-08-16 10:40 UTC, Runidan commented
> 

Добавил два статичных метода

2022-08-16 10:58 UTC, PonomareVlad requested changes
Нужно проверить соответствие спецификации [`Promise.resolve()`](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Promise/resolve)

> Если переданное значение является thenable - объект (т.е. имеет метод ["then" method](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Promise/then)), возвращаемый промис будет следовать thenable - объекту, принимая своё состояние; в ином случае возвращаемый промис будет выполнен с переданным значением.

```js
const url = 'https://api.ipify.org?format=json'

Promise.resolve(fetch(url)).then(response => response.json()).then(console.debug) // {ip: ...}

CustomPromise.resolve(fetch(url)).then(response => response.json()).then(console.debug)
// CustomPromise {state: "pending", result: undefined, onFulfilledFn: [], onRejectedFn: []}
```

2022-08-24 08:14 UTC, PonomareVlad approved these changes

2022-08-25 07:08 UTC, merged